version: "master-{build}"

os: Visual Studio 2017
platform:
  - x64

environment:
  matrix:
    - ruby_version: "25-x64"

clone_folder: c:\projects\mixlib-archive
clone_depth: 1
skip_tags: true
branches:
  only:
    - master

install:
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - echo %PATH%
  - ruby --version
  - gem --version
  - gem update --system
  - gem install bundler --quiet --no-document
  - bundler --version

build_script:
  - bundle install

test_script:
  - bundle exec rake
